// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var $$Array = require("bs-platform/lib/js/array.js");
var Curry = require("bs-platform/lib/js/curry.js");
var Lib$AdventOfCode19 = require("./Lib.bs.js");

function calculateFuel(mass) {
  var fuel = (mass / 3 | 0) - 2 | 0;
  var match = fuel <= 0;
  if (match) {
    return 0;
  } else {
    return fuel + calculateFuel(fuel) | 0;
  }
}

var __x = $$Array.to_list(Curry._1(Lib$AdventOfCode19.Lib.openFile, "input1.txt").split("\n"));

var __x$1 = List.filter((function (str) {
          return str !== "";
        }))(__x);

var __x$2 = List.map(Lib$AdventOfCode19.Lib.fromString, __x$1);

console.log(List.fold_left((function (total, mass) {
            return total + calculateFuel(mass) | 0;
          }), 0, __x$2));

var Lib = Lib$AdventOfCode19.Lib;

exports.Lib = Lib;
exports.calculateFuel = calculateFuel;
/*  Not a pure module */
