// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var Curry = require("bs-platform/lib/js/curry.js");
var Lib$AdventOfCode19 = require("./Lib.bs.js");
var Intcode$AdventOfCode19 = require("./Intcode.bs.js");

var memory = Curry._2(Intcode$AdventOfCode19.Intcode.run, 5, $$Array.map(Lib$AdventOfCode19.Lib.fromString, Curry._1(Lib$AdventOfCode19.Lib.openFile, "input5.txt").split(",")));

console.log("Done");

var Lib = Lib$AdventOfCode19.Lib;

var $$String = Intcode$AdventOfCode19.$$String;

var Intcode = Intcode$AdventOfCode19.Intcode;

exports.Lib = Lib;
exports.$$String = $$String;
exports.Intcode = Intcode;
exports.memory = memory;
/* memory Not a pure module */
